apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vjb9zrfsz-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vjb9zrfsz-dotnet-basic-gitops